//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogInApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail
    {
        public int Id { get; set; }

        [Required(ErrorMessage="Please provide UserName",AllowEmptyStrings=false)]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Please provide Password", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [StringLength(50,MinimumLength=3,ErrorMessage="Password must be 3 char long..")]
        public string Password { get; set; }  
      
        //[Compare("Password", ErrorMessage ="Confirm password dose not match.")]
        //[DataType(DataType.Password)]
        //public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Please provide Email", AllowEmptyStrings = false)]
        public string EmailId { get; set; }

        public int PhoneNo { get; set; }
    }
}
